// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt66w1ommFhyzwSwwjXCDtz6r0j5Ejgpg',
    appId: '1:263521374833:web:923982390f26fe04ec01d0',
    messagingSenderId: '263521374833',
    projectId: 'synq-d21a3',
    authDomain: 'synq-d21a3.firebaseapp.com',
    storageBucket: 'synq-d21a3.firebasestorage.app',
    measurementId: 'G-1PJ0TBXNP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZm-SzZ7QutBxzjLwdOStPGHrMCJttdao',
    appId: '1:263521374833:android:ff76ae5f81b031c4ec01d0',
    messagingSenderId: '263521374833',
    projectId: 'synq-d21a3',
    storageBucket: 'synq-d21a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUAgBd6kAObZETejwWrlt9UrTvc0r34J4',
    appId: '1:263521374833:ios:cf406a94eb189d4bec01d0',
    messagingSenderId: '263521374833',
    projectId: 'synq-d21a3',
    storageBucket: 'synq-d21a3.firebasestorage.app',
    iosBundleId: 'com.aashish.synq.synq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUAgBd6kAObZETejwWrlt9UrTvc0r34J4',
    appId: '1:263521374833:ios:cf406a94eb189d4bec01d0',
    messagingSenderId: '263521374833',
    projectId: 'synq-d21a3',
    storageBucket: 'synq-d21a3.firebasestorage.app',
    iosBundleId: 'com.aashish.synq.synq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt66w1ommFhyzwSwwjXCDtz6r0j5Ejgpg',
    appId: '1:263521374833:web:baded0d1b9c9fc54ec01d0',
    messagingSenderId: '263521374833',
    projectId: 'synq-d21a3',
    authDomain: 'synq-d21a3.firebaseapp.com',
    storageBucket: 'synq-d21a3.firebasestorage.app',
    measurementId: 'G-4SXR2LFQ2Z',
  );
}
